version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0
  docker: circleci/docker@2.1.3

jobs:
  build:
    docker: &docker
      - image: cimg/python:3.10.6
    steps:
      - checkout
      - setup_remote_docker
      # - run: python --version
      - &restore_venv_cache
        restore_cache:
          keys:
            # when lock files change, use increasingly general
            # patterns to restore cache
            - &python_cache_key
              # yamllint disable-line rule:line-length
              python-3.10-packages-v1-{{ .Branch }}-{{ checksum "requirements.in" }}-{{ checksum "requirements.txt" }}
              # yamllint disable-line rule:line-length
            - python-3.10-packages-v1-{{ .Branch }}-{{ checksum "requirements.in" }}-
            - python-3.10-packages-v1-{{ .Branch }}-
            - python-3.10-packages-v1-main-
      - &build
        run:
          name: Build Image
          # machine:
            # docker_layer_caching: true
          command: |
            make image
  test:
    docker: &docker
      - image: cimg/python:3.10.6
    steps:
      - setup_remote_docker
      - run:
          name: Dry run queries
          command: |
            make test

workflows:
  version: 2
  build:
    jobs: &build_jobs
      - build:
          context: data-eng-circleci-tests
      - test:
          requires:
            - build
